### ISSUE TITLE
pyCore import Error

### ISSUE THREAD

**Issue by ZeliangSu** [v1kko/daetools#5]
Hi all,
I would like to build a V2.2.0 on a windows machine, then ran into the following error. I made sure that I cleanly installed the python3.7 and even the pycore(not sure they are related), but the problem remained. Any help would be greatly appreciated. Thanks!

> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "D:\ProgramData\Anaconda3\envs\MPET\lib\site-packages\daetools-2.2.0-py3.7-win-amd64.egg\daetools\pyDAE\__init__.py", line 20, in <module>
>     import pyCore
> ModuleNotFoundError: No module named 'pyCore'

**Comment by v1kko** [comment]
Hi @ZeliangSu, I made this repository a while ago to ensure availability of version 1.9.3 on conda for newer python versions (on linux only) as the project seemed stale and it was needed as a dependency by some other projects. 

It's great news that there is a new version 2.2.0 now! But I am not the maintainer or even the developer of daetools, so I would have to redirect you to https://daetools.sourceforge.io as that seems to be where the new 2.2.0 version lives
